name: Testing

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'

jobs:
  setup:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          clean: false

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

  quality:
    runs-on: self-hosted

    steps:
      - name: Run eslint
        run: npm run lint
      
      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test:
    runs-on: self-hosted

    steps:
      - name: Run unit tests
        run: npm run test